### ISSUE TITLE
Error handling for file read

### ISSUE THREAD

**Issue by nilsstre** [aaronsum1102/Personify#22]
You should probably but the lines were you open and read files in a try-catch block. Stuff can happen to your files so it's nice if the program doesn't just quit. The same for when you write to file.

Example were this could be a good idea:

https://github.com/aaronsum1102/Personify/blob/6017829463035d659ae54fd3534b0606b00e85c7/src/com/Personify/textView/Menu.java#L21-L23

**Comment by aaronsum1102** [comment]
Done. The exception handling was added in the branch. Refer to commit e0c2158344c14abe3a7fe5349fa6102fb59bade6.
