### ISSUE TITLE
Handling of motivational quotes

### ISSUE THREAD

**Issue by nilsstre** [aaronsum1102/Personify#8]
You should probably think about implementing a way to import your motivational quotes from a separate file rather than including them in your code.

https://github.com/aaronsum1102/Personify/blob/e3461fb531e49b09868d7e90105a823d7c3aa7f4/src/Motivation.java#L20-25

**Comment by aaronsum1102** [comment]
Thanks for the suggestion. Will try to do add it next upload.

**Comment by aaronsum1102** [comment]
Done. refer to commit 59604f5.
